version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: issue_tracker
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
